In [1]:
import pandas as pd
import os

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '01_data_understanding.ipynb',
 'olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [3]:
orders = pd.read_csv('olist_orders_dataset.csv')

In [4]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
orders.shape

(99441, 8)

In [6]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [7]:
orders.shape

(99441, 8)

In [8]:
orders['order_id'].nunique()

99441

In [9]:
customers = pd.read_csv('olist_customers_Dataset.csv')

In [10]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [11]:
customers.shape

(99441, 5)

In [12]:
customers['customer_id'].nunique()

99441

In [13]:
customers['customer_unique_id'].nunique()

96096

In [14]:
order_items = pd.read_csv('olist_order_items_dataset.csv')

In [15]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

order_items.shape

In [16]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [17]:
order_items.shape

(112650, 7)

In [18]:
order_items['order_id'].nunique()

98666

In [19]:
order_items['order_item_id'].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [21]:
products = pd.read_csv('olist_products_dataset.csv')

In [22]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [23]:
products.shape

(32951, 9)

In [24]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [25]:
category_translation = pd.read_csv(
    'product_category_name_translation.csv'
)

In [26]:
category_translation.head(10)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
5           esporte_lazer                sports_leisure
6              perfumaria                     perfumery
7   utilidades_domesticas                    housewares
8               telefonia                     telephony
9      relogios_presentes                 watches_gifts

In [27]:
category_translation.shape

(71, 2)

In [28]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [29]:
products['product_id'].nunique()

32951

In [30]:
category_translation['product_category_name'].nunique()

71

In [31]:
sellers = pd.read_csv('olist_sellers_dataset.csv')

In [32]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [33]:
sellers.shape

(3095, 4)

In [34]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [35]:
sellers['seller_id'].nunique()

3095

In [36]:
order_payment = pd.read_csv('olist_order_payments_dataset.csv')

In [37]:
order_payment.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [38]:
order_payment.shape

(103886, 5)

In [39]:
order_payment.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [40]:
order_payment['order_id'].nunique()

99440

In [41]:
order_payment['payment_sequential'].value_counts().sort_index()

payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
16        6
17        6
18        6
19        6
20        4
21        4
22        3
23        2
24        2
25        2
26        2
27        1
28        1
29        1
Name: count, dtype: int64

In [43]:
order_payment.groupby('order_id').size().value_counts().sort_index()

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [44]:
print(order_payment.shape)
print(order_payment.columns.tolist())
print(order_payment.isnull().sum())

(103886, 5)
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [45]:
%whos

Variable               Type         Data/Info
---------------------------------------------
category_translation   DataFrame    Shape: (71, 2)
customers              DataFrame    Shape: (99441, 5)
order_items            DataFrame    Shape: (112650, 7)
order_payment          DataFrame    Shape: (103886, 5)
orders                 DataFrame    Shape: (99441, 8)
os                     module       <module 'os' (frozen)>
pd                     module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
products               DataFrame    Shape: (32951, 9)
sellers                DataFrame    Shape: (3095, 4)

In [46]:
tables = {
    "orders": orders,
    "customers": customers,
    "order_items": order_items,
    "order_payment": order_payment,
    "products": products,
    "sellers": sellers
}

for name, df in tables.items():
    print(f"\n{name.upper()}")
    print("Rows:", len(df))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

ORDERS
Rows: 99441
Duplicate rows: 0
Missing values: 4908

CUSTOMERS
Rows: 99441
Duplicate rows: 0
Missing values: 0

ORDER_ITEMS
Rows: 112650
Duplicate rows: 0
Missing values: 0

ORDER_PAYMENT
Rows: 103886
Duplicate rows: 0
Missing values: 0

PRODUCTS
Rows: 32951
Duplicate rows: 0
Missing values: 2448

SELLERS
Rows: 3095
Duplicate rows: 0
Missing values: 0

In [47]:
orders.isnull().sum()
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [48]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [51]:
import sqlite3

conn = sqlite3.connect("ecommerce.db")

In [53]:
orders.to_sql("orders", conn, if_exists="replace", index=False)
order_items.to_sql("order_items", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
customers.to_sql("customers", conn, if_exists="replace", index=False)

99441

In [54]:
order_items.to_sql("order_items", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
customers.to_sql("customers", conn, if_exists="replace", index=False)

99441

In [55]:
pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)

          name
0       orders
1  order_items
2     products
3    customers

In [56]:
pd.read_sql_query("""
Select count(*) as total_orders
from orders;
""", conn)

   total_orders
0         99441

In [57]:
pd.read_sql_query("""
SELECT
    strftime('%Y', order_purchase_timestamp) AS year,
    COUNT(*) AS total_orders
FROM orders
GROUP BY year
ORDER BY year;
""", conn)

   year  total_orders
0  2016           329
1  2017         45101
2  2018         54011

In [58]:
pd.read_sql_query("""
SELECT
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items;
""", conn)

   total_revenue
0     13591643.7

In [59]:
pd.read_sql_query("""
SELECT
    ROUND(SUM(price), 2) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(price) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM order_items;
""", conn)

   total_revenue  total_orders  average_order_value
0     13591643.7         98666               137.75

In [60]:
kpi = pd.read_sql_query("""
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(price), 2) AS product_revenue,
    ROUND(SUM(price) / COUNT(DISTINCT order_id), 2) AS average_order_value,
    COUNT(DISTINCT product_id) AS unique_products,
    COUNT(DISTINCT seller_id) AS unique_sellers
FROM order_items;
""", conn)

kpi

,total_orders,product_revenue,average_order_value,unique_products,unique_sellers
0,98666,13591643.7,137.75,32951,3095

In [61]:
pd.read_sql_query("""
SELECT
    p.product_category_name AS category,
    COUNT(DISTINCT oi.order_id) AS orders,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
LEFT JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_category_name IS NOT NULL
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;
""", conn)

                 category  orders     revenue
0            beleza_saude    8836  1258681.34
1      relogios_presentes    5624  1205005.68
2         cama_mesa_banho    9417  1036988.68
3           esporte_lazer    7720   988048.97
4  informatica_acessorios    6689   911954.32
5        moveis_decoracao    6449   729762.49
6              cool_stuff    3632   635290.85
7   utilidades_domesticas    5884   632248.66
8              automotivo    3897   592720.11
9      ferramentas_jardim    3518   485256.46

In [64]:
order_payment.to_sql("order_payment", conn, if_exists="replace", index=False)

print(pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn))

            name
0         orders
1    order_items
2       products
3      customers
4  order_payment

In [65]:
# 1. Payment Methods
payment_analysis = pd.read_sql_query("""
SELECT
    payment_type,
    COUNT(*) AS payment_records,
    ROUND(SUM(payment_value), 2) AS payment_value
FROM order_payment
GROUP BY payment_type
ORDER BY payment_value DESC;
""", conn)

# 2. Order Status
status_analysis = pd.read_sql_query("""
SELECT
    order_status,
    COUNT(*) AS orders
FROM orders
GROUP BY order_status
ORDER BY orders DESC;
""", conn)

# 3. Delivery Performance
delivery_analysis = pd.read_sql_query("""
SELECT
    ROUND(AVG(
        julianday(order_delivered_customer_date)
        - julianday(order_purchase_timestamp)
    ), 2) AS avg_delivery_days,
    
    ROUND(AVG(
        julianday(order_estimated_delivery_date)
        - julianday(order_purchase_timestamp)
    ), 2) AS avg_estimated_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
""", conn)

payment_analysis, status_analysis, delivery_analysis

(  payment_type  payment_records  payment_value
 0  credit_card            76795    12542084.19
 1       boleto            19784     2869361.27
 2      voucher             5775      379436.87
 3   debit_card             1529      217989.79
 4  not_defined                3           0.00,
   order_status  orders
 0    delivered   96478
 1      shipped    1107
 2     canceled     625
 3  unavailable     609
 4     invoiced     314
 5   processing     301
 6      created       5
 7     approved       2,
    avg_delivery_days  avg_estimated_days
 0              12.56               23.74)

In [68]:
pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)

            name
0         orders
1    order_items
2       products
3      customers
4  order_payment

In [69]:
reviews = pd.read_csv("olist_order_reviews_dataset.csv")

reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [70]:
reviews.to_sql(
    "order_reviews",
    conn,
    if_exists="replace",
    index=False
)

99224

In [71]:
pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)

            name
0         orders
1    order_items
2       products
3      customers
4  order_payment
5  order_reviews

In [72]:
pd.read_sql_query("""
SELECT 
    review_score,
    COUNT(*) AS reviews
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;
""", conn)

   review_score  reviews
0             1    11424
1             2     3151
2             3     8179
3             4    19142
4             5    57328

In [73]:
pd.read_sql_query("""
SELECT 
    ROUND(AVG(review_score), 2) AS avg_review_score
FROM order_reviews;
""", conn)

   avg_review_score
0              4.09

In [74]:
pd.read_sql_query("""
SELECT
    CASE
        WHEN review_score >= 4 THEN 'Positive'
        WHEN review_score <= 2 THEN 'Negative'
        ELSE 'Neutral'
    END AS sentiment,
    COUNT(*) AS reviews
FROM order_reviews
GROUP BY sentiment
ORDER BY reviews DESC;
""", conn)

  sentiment  reviews
0  Positive    76470
1  Negative    14575
2   Neutral     8179